# Generated by Django 4.0.2 on 2022-03-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='')),
                ('PhotoURL', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=200)),
                ('FirstName', models.CharField(max_length=200, verbose_name='First Name')),
                ('MiddleName', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('LastName', models.CharField(max_length=200, verbose_name='Last Name')),
                ('Nationality', models.CharField(max_length=200, verbose_name='Nationality')),
                ('City', models.CharField(max_length=200)),
                ('Street', models.CharField(max_length=200, verbose_name='Street')),
                ('Permit', models.CharField(choices=[('Residence', 'Residence'), ('Visit', 'Visit')], max_length=200, verbose_name='Home Address')),
                ('Emirate', models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Dubai', 'Dubai'), ('Sharjah ', 'Sharjah '), ('Ajman', 'Ajman'), ('Umm Al Quwain ', 'Umm Al Quwain '), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Fujairah', 'Fujairah')], max_length=200, verbose_name='Emirate')),
                ('PhoneNumber', models.CharField(max_length=200, verbose_name='Phone Number')),
                ('EmailAddress', models.EmailField(max_length=200, verbose_name='Email')),
                ('EmploymentStatus', models.CharField(choices=[('Full time', 'Full time'), ('Part time ', 'Part time '), ('Not applicable', 'Not applicable'), ('Seeker', 'Seeker'), ('Own a business', 'Own a business'), ('Self-employer', 'Self-employer')], max_length=200, verbose_name='Religion')),
                ('CompanyName', models.EmailField(max_length=200, verbose_name='Company Name')),
                ('DoYouKnowAboutTAE', models.BooleanField(default=False, verbose_name='Do You Know About TAE')),
                ('Advice', models.TextField(max_length=200)),
            ],
        ),
    ]
