# Generated by Django 4.0.2 on 2022-03-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAEApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredStudent',
            new_name='Member',
        ),
    ]
