# Generated by Django 4.0.2 on 2022-05-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAEApp', '0003_remove_gallery_photourl_alter_gallery_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='images/News')),
                ('Title', models.CharField(max_length=50)),
                ('Description1', models.TextField(max_length=200)),
                ('Description2', models.TextField(max_length=200)),
                ('PublishDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
