# Generated by Django 4.0.2 on 2022-05-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAEApp', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('PhoneUEA', models.CharField(blank=True, max_length=50)),
                ('PhoneTZ', models.CharField(blank=True, max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('AgentName', models.CharField(max_length=50)),
                ('AgentPhoneTZ', models.CharField(blank=True, max_length=50)),
                ('AgentPhoneUAE', models.CharField(blank=True, max_length=50)),
                ('ServiceType', models.CharField(max_length=50)),
                ('VisaType', models.CharField(max_length=50)),
                ('VisaStatus', models.CharField(max_length=50)),
                ('AmountPaidTZ', models.CharField(blank=True, max_length=50)),
                ('AmountPaidUAE', models.CharField(blank=True, max_length=50)),
                ('Description', models.TextField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complain2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TAENumber', models.CharField(max_length=50)),
                ('FullName', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('CompanyOrSponsor', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('JobYears', models.IntegerField()),
                ('Complain', models.TextField(max_length=100)),
                ('TakenSteps', models.TextField(max_length=100)),
                ('Recommendation', models.TextField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='Description2',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='Photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
