# Generated by Django 4.0.2 on 2022-05-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAEApp', '0006_alter_complain1_servicetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain1',
            old_name='PhoneUEA',
            new_name='PhoneUAE',
        ),
    ]
