# Generated by Django 4.0.2 on 2022-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAEApp', '0007_rename_phoneuea_complain1_phoneuae'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionApplicats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=200, verbose_name='Membership Code')),
                ('FirstName', models.CharField(max_length=200, verbose_name='First Name')),
                ('MiddleName', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('LastName', models.CharField(max_length=200, verbose_name='Last Name')),
                ('EmirateID', models.ImageField(upload_to='images', verbose_name='Attach Emirate ID')),
                ('VisaType', models.CharField(choices=[('Golden visa', 'Golden visa'), ('Residence visa', 'Residence visa'), ('Visit visa ', 'Visit visa '), ('Transit visa', 'Transit visa')], max_length=200, verbose_name='Visa Type')),
                ('Education', models.CharField(choices=[('Secondary school', 'Secondary school'), ('High school', 'High school'), ('Certificate ', 'Certificate '), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=200, verbose_name='Education')),
                ('Emirate', models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Dubai', 'Dubai'), ('Sharjah ', 'Sharjah '), ('Ajman', 'Ajman'), ('Umm Al Quwain ', 'Umm Al Quwain '), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Fujairah', 'Fujairah')], max_length=200, verbose_name='Emirate')),
                ('Position', models.CharField(choices=[('Chairman of the association', 'Chairman of the association'), ('Vice Chairman of the Association', 'Vice Chairman of the Association'), ('Secretary General', 'Secretary General'), ('Deputy Secretary General', 'Deputy Secretary General'), ('Treasurer', 'Treasurer'), ('Assistant Treasurer', 'Assistant Treasurer'), ('Chairman of the Chairman of Cultural and Social Welfare Committee', 'Chairman of the Chairman of Cultural and Social Welfare Committee'), ('Chairman of the Chairman of Budget and Finance Committee', 'Chairman of the Chairman of Budget and Finance Committee'), ('Chairman of the Chairman of knowledge and Publicity Committee', 'Chairman of the Chairman of knowledge and Publicity Committee'), ('Chairman of the Chairman of Homeland investment committee', 'Chairman of the Chairman of Homeland investment committee'), ('Committee member of Cultural and Social Welfare Committee', 'Committee member of Cultural and Social Welfare Committee'), ('Committee member of Budget and Finance Committee', 'Committee member of Budget and Finance Committee'), ('Committee member of knowledge and Publicity Committee', 'Committee member of knowledge and Publicity Committee'), ('Committee member of Homeland investment committee', 'Committee member of Homeland investment committee')], max_length=100, verbose_name='Position')),
                ('EmploymentStatus', models.CharField(choices=[('Full time', 'Full time'), ('Part time ', 'Part time '), ('Not applicable', 'Not applicable'), ('Seeker', 'Seeker'), ('Own a business', 'Own a business'), ('Self-employer', 'Self-employer')], max_length=200, verbose_name='Religion')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsMember', models.BooleanField(default=False, verbose_name='Are you a TAE member')),
                ('Code', models.CharField(blank=True, max_length=200)),
                ('FullName', models.CharField(max_length=200, verbose_name='Full Name')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=500)),
                ('Nationality', models.CharField(max_length=200, verbose_name='Nationality')),
                ('Emirate', models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Dubai', 'Dubai'), ('Sharjah ', 'Sharjah '), ('Ajman', 'Ajman'), ('Umm Al Quwain ', 'Umm Al Quwain '), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Fujairah', 'Fujairah')], max_length=200, verbose_name='Emirate')),
                ('Feedback', models.TextField(max_length=100, verbose_name='Your Feedback')),
                ('ShareWithOthers', models.BooleanField(default=False, verbose_name='Do you want to share your feedback with others yes/no')),
            ],
        ),
        migrations.AlterField(
            model_name='complain1',
            name='VisaType',
            field=models.CharField(choices=[('Golden visa', 'Golden visa'), ('Residence visa', 'Residence visa'), ('Visit visa ', 'Visit visa '), ('Transit visa', 'Transit visa')], max_length=50),
        ),
    ]
