# Generated by Django 4.0.2 on 2022-05-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAEApp', '0008_electionapplicats_feedback_alter_complain1_visatype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectionApplicats',
            new_name='ElectionApplicant',
        ),
    ]
