# Generated by Django 4.0.2 on 2022-07-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAEApp', '0010_content_frontpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='images')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=200)),
                ('PublishDate', models.DateTimeField(auto_now_add=True)),
                ('EndDate', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=False)),
                ('GeneratedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='complain1',
            name='ServiceType',
            field=models.CharField(choices=[('Kazi UAE', 'Kazi UAE'), ('Kununua Bidhaa', 'Kununua Bidhaa'), ('Kuuza Bidhaa', 'Kuuza Bidhaa'), ('Matibabu', 'Matibabu'), ('Masomo', 'Masomo'), ('Mengine', 'Mengine')], max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='Description1',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='content',
            name='Title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electionapplicant',
            name='EmploymentStatus',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time ', 'Part time '), ('Not applicable', 'Not applicable'), ('Job Seeker', 'Job Seeker'), ('Own a business', 'Own a business'), ('Self-employer', 'Self-employer')], max_length=200, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Photo',
            field=models.ImageField(upload_to='images/Events/Gallery/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='EmploymentStatus',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time ', 'Part time '), ('Not applicable', 'Not applicable'), ('Job Seeker', 'Job Seeker'), ('Own a business', 'Own a business'), ('Self-employer', 'Self-employer')], max_length=200, verbose_name='Religion'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='images/Events/')),
                ('Title', models.CharField(max_length=50)),
                ('Description1', models.TextField(max_length=200)),
                ('Description2', models.TextField(blank=True, max_length=200)),
                ('PublishDate', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAEApp.category', verbose_name='Category')),
                ('Gallery', models.ManyToManyField(to='TAEApp.Gallery')),
            ],
        ),
    ]
