# Generated by Django 4.0.2 on 2022-07-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAEApp', '0011_article_category_otp_alter_complain1_servicetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='Code',
            field=models.CharField(max_length=200),
        ),
    ]
