# Generated by Django 4.0.2 on 2022-07-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAEApp', '0012_alter_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='MemberID',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='otp',
            name='Code',
            field=models.CharField(max_length=50),
        ),
    ]
