# Generated by Django 4.0.2 on 2022-07-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAEApp', '0013_otp_memberid_alter_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCommitteeApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=200, verbose_name='Membership Code')),
                ('FirstName', models.CharField(max_length=200, verbose_name='First Name')),
                ('MiddleName', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('LastName', models.CharField(max_length=200, verbose_name='Last Name')),
                ('VisaType', models.CharField(choices=[('Golden visa', 'Golden visa'), ('Residence visa', 'Residence visa'), ('Visit visa ', 'Visit visa '), ('Transit visa', 'Transit visa')], max_length=200, verbose_name='Visa Type')),
                ('Education', models.CharField(choices=[('Secondary school', 'Secondary school'), ('High school', 'High school'), ('Certificate ', 'Certificate '), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=200, verbose_name='Education')),
                ('Emirate', models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Dubai', 'Dubai'), ('Sharjah ', 'Sharjah '), ('Ajman', 'Ajman'), ('Umm Al Quwain ', 'Umm Al Quwain '), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Fujairah', 'Fujairah')], max_length=200, verbose_name='Emirate')),
                ('EmploymentStatus', models.CharField(choices=[('Full time', 'Full time'), ('Part time ', 'Part time '), ('Not applicable', 'Not applicable'), ('Job Seeker', 'Job Seeker'), ('Own a business', 'Own a business'), ('Self-employer', 'Self-employer')], max_length=200, verbose_name='Religion')),
            ],
        ),
        migrations.AlterField(
            model_name='electionapplicant',
            name='Position',
            field=models.CharField(choices=[('Chairman of the association', 'Chairman of the association'), ('Vice Chairman of the Association', 'Vice Chairman of the Association'), ('Secretary General', 'Secretary General'), ('Deputy Secretary General', 'Deputy Secretary General'), ('Treasurer', 'Treasurer'), ('Assistant Treasurer', 'Assistant Treasurer'), ('Education, Cultural and Social Welfare Committee', 'Education, Cultural and Social Welfare Committee'), ('Finance and Planning Committee', 'Finance and Planning Committee'), ('Publicity and Communication Committee', 'Publicity and Communication Committee'), ('Homeland investment committee', 'Homeland investment committee')], max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Advice',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='Permit',
            field=models.CharField(choices=[('Residence', 'Residence'), ('Visit', 'Visit'), ('UAE National', 'UAE National'), ('AGCC National', 'AGCC National')], max_length=200, verbose_name='Home Address'),
        ),
    ]
