# Generated by Django 4.0.2 on 2022-07-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAEApp', '0014_electioncommitteeapplicant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailFrom', models.CharField(max_length=50)),
                ('EmailPassword', models.CharField(max_length=50)),
                ('SMTPHOST', models.CharField(max_length=50)),
                ('SMTPPort', models.IntegerField()),
            ],
        ),
    ]
